global:
  postgresql:
    existingSecret: postgres-passwords
postgresql:
  username: cryptofolio
  database: cryptofolio
  podAntiAffinityPreset: hard
  resources:
    limits:
      memory: 1Gi
persistence:
  size: 30Gi