# This script can be used to start build the Docker images.

version: "3.8"

services:

  cryptofolio-job-collector:
    build:
      # You can override the build context (where the source code is) by defining a JOB_COLLECTOR_BUILD_CONTEXT environment variable.
      context: ${JOB_COLLECTOR_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Collector.Job/Dockerfile
    image: registry.digitalocean.com/cryptofolio/jobs/collector:${JOB_COLLECTOR_TAG:-latest}

  cryptofolio-job-handlers:
    build:
      # You can override the build context (where the source code is) by defining a JOB_HANDLERS_BUILD_CONTEXT environment variable.
      context: ${JOB_HANDLERS_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Handlers.Job/Dockerfile
    image: registry.digitalocean.com/cryptofolio/jobs/handlers:${JOB_HANDLERS_TAG:-latest}