# This script can be used to start build the Docker images.

version: "3.8"

services:

  cryptofolio-api:
    build:
      # You can override the build context (where the source code is) by defining a API_BUILD_CONTEXT environment variable.
      context: ${API_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Api/Dockerfile
      args:
        - VERSION=$API_VERSION
    image: ${REGISTRY:-registry.digitalocean.com/cryptofolio}/${API_REPOSITORY:-api}:${API_TAG:-latest}

  cryptofolio-app:
    build:
      # You can override the build context (where the source code is) by defining a APP_BUILD_CONTEXT environment variable.
      context: ${APP_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.App/Dockerfile
      args:
        - VERSION=$APP_VERSION
    image: ${REGISTRY:-registry.digitalocean.com/cryptofolio}/${APP_REPOSITORY:-app}:${APP_TAG:-latest}

  cryptofolio-job-collector:
    build:
      # You can override the build context (where the source code is) by defining a JOB_COLLECTOR_BUILD_CONTEXT environment variable.
      context: ${JOB_COLLECTOR_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Collector.Job/Dockerfile
      args:
        - VERSION=$JOB_COLLECTOR_VERSION
    image: ${REGISTRY:-registry.digitalocean.com/cryptofolio}/${JOB_COLLECTOR_REPOSITORY:-jobs/collector}:${JOB_COLLECTOR_TAG:-latest}

  cryptofolio-job-handlers:
    build:
      # You can override the build context (where the source code is) by defining a JOB_HANDLERS_BUILD_CONTEXT environment variable.
      context: ${JOB_HANDLERS_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Handlers.Job/Dockerfile
      args:
        - VERSION=$JOB_HANDLERS_VERSION
    image: ${REGISTRY:-registry.digitalocean.com/cryptofolio}/${JOB_HANDLERS_REPOSITORY:-jobs/handlers}:${JOB_HANDLERS_TAG:-latest}

  cryptofolio-job-balances:
    build:
      # You can override the build context (where the source code is) by defining a JOB_BALANCES_BUILD_CONTEXT environment variable.
      context: ${JOB_BALANCES_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Balances.Job/Dockerfile
      args:
        - VERSION=$JOB_BALANCES_VERSION
    image: ${REGISTRY:-registry.digitalocean.com/cryptofolio}/${JOB_BALANCES_REPOSITORY:-jobs/balances}:${JOB_BALANCES_TAG:-latest}