# This script can be used to start build the Docker images.

version: "3.8"

services:

  cryptofolio-api:
    build:
      # You can override the build context (where the source code is) by defining a API_BUILD_CONTEXT environment variable.
      context: ${API_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Api/Dockerfile
      args:
        # Make sure that you have defined the HTTP_PROXY environment variable on your host.
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTP_PROXY
    image: registry.digitalocean.com/cryptofolio/api:${API_TAG:-latest}

  cryptofolio-app:
    build:
      # You can override the build context (where the source code is) by defining a APP_BUILD_CONTEXT environment variable.
      context: ${APP_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.App/Dockerfile
      args:
        # Make sure that you have defined the HTTP_PROXY environment variable on your host.
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTP_PROXY
    image: registry.digitalocean.com/cryptofolio/app:${APP_TAG:-latest}

  cryptofolio-job-collector:
    build:
      # You can override the build context (where the source code is) by defining a JOB_COLLECTOR_BUILD_CONTEXT environment variable.
      context: ${JOB_COLLECTOR_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Collector.Job/Dockerfile
      args:
        # Make sure that you have defined the HTTP_PROXY environment variable on your host.
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTP_PROXY
    image: registry.digitalocean.com/cryptofolio/jobs/collector:${JOB_COLLECTOR_TAG:-latest}

  cryptofolio-job-handlers:
    build:
      # You can override the build context (where the source code is) by defining a JOB_HANDLERS_BUILD_CONTEXT environment variable.
      context: ${JOB_HANDLERS_BUILD_CONTEXT:-../}
      dockerfile: src/Cryptofolio.Handlers.Job/Dockerfile
      args:
        # Make sure that you have defined the HTTP_PROXY environment variable on your host.
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTP_PROXY
    image: registry.digitalocean.com/cryptofolio/jobs/handlers:${JOB_HANDLERS_TAG:-latest}