replicaCount: 3
podAntiAffinityPreset: hard
resources:
  requests:
    cpu: 10m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi
heapOpts: -Xmx1g -Xms1g
deleteTopicEnable: true
autoCreateTopicsEnable: false
maxMessageBytes: _104857600
persistence:
  size: 30Gi
serviceAccount:
  create: false
zookeeper:
  enabled: false
externalZookeeper:
  servers:
    - zookeeper-0.zookeeper-headless.default.svc.cluster.local
    - zookeeper-1.zookeeper-headless.default.svc.cluster.local
    - zookeeper-2.zookeeper-headless.default.svc.cluster.local