apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptofolio-collector-job.fullname" . }}-config
  labels:
    {{- include "cryptofolio-collector-job.labels" . | nindent 4 }}
data:
  appsettings.{{ .Values.jobs.collector.environment }}.json: |
    {
      "Serilog": {
        "MinimumLevel": {
          "Default": "{{ .Values.jobs.collector.config.logLevel }}"
        },
        "Elasticsearch": {
          "Nodes": {{ .Values.jobs.collector.config.elasticsearch.nodes | toJson }}
        }
      },
      "ConnectionStrings": {
        "Redis": "{{ .Values.jobs.collector.config.connectionStrings.redis }}"
      },
      "Kafka": {
        "Producer": {
          "BootstrapServers": "{{ .Values.jobs.collector.config.kafka.bootstrapServers | join "," }}"
        },
        "Consumer": {
          "BootstrapServers": "{{ .Values.jobs.collector.config.kafka.bootstrapServers | join "," }}"
        }
      },
      "Elasticsearch": {
        "Nodes": {{ .Values.jobs.collector.config.elasticsearch.nodes | toJson }}
      },
      "Data": {
        "CronCheckIntervalMs": {{ .Values.jobs.collector.config.data.cronCheckIntervalMs }},
        "InvalidCronCheckIntervalMs": {{ .Values.jobs.collector.config.data.invalidCronCheckIntervalMs }},
        "Schedules": {
          "Cryptofolio.Infrastructure.Data.AssetDataRequest": "{{ .Values.jobs.collector.config.data.schedules.assetDataRequest }}",
          "Cryptofolio.Infrastructure.Data.AssetTickerDataRequest": "{{ .Values.jobs.collector.config.data.schedules.assetTickerDataRequest }}",
          "Cryptofolio.Infrastructure.Data.ExchangeDataRequest": "{{ .Values.jobs.collector.config.data.schedules.exchangeDataRequest }}"
        }
      },
      "Coingecko": {
        "ApiUri": "{{ .Values.jobs.collector.config.coingecko.apiUri }}",
        "RateLimiterKey": "{{ .Values.jobs.collector.config.coingecko.rateLimiterKey }}",
        "RateLimiterKeyExiprationSeconds": {{ .Values.jobs.collector.config.coingecko.rateLimiterKeyExiprationSeconds }},
        "RateLimiterMaxValue": {{ .Values.jobs.collector.config.coingecko.rateLimiterMaxValue }},
        "RateLimiterCheckIntervalMs": {{ .Values.jobs.collector.config.coingecko.rateLimiterCheckIntervalMs }}
      }
    }