apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryptofolio-api.fullname" . }}
  labels:
    {{- include "cryptofolio-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cryptofolio-api.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryptofolio-app.fullname" . }}
  labels:
    {{- include "cryptofolio-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cryptofolio-app.selectorLabels" . | nindent 4 }}